export const ACTION_ADD_PAGES = 'ADD_PAGES';
export const ACTION_REMOVE_ALL_PAGES = 'REMOVE_ALL_PAGES';
export const ACTION_REMOVE_PAGE = 'REMOVE_PAGE';
export const ACTION_UPDATE_OR_ADD_PAGE = 'UPDATE_OR_ADD_PAGE';
